### ISSUE TITLE
Question: how does it work?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [wotomas/VoiceRipple#4]
What's the main API that makes the ripple become larger and smaller based on what you say?
Where in the code to look at ? 

Just curious...

**Comment by wotomas** [comment]
@AndroidDeveloperLB all the source code is inside the ripplelibrary directory! 
```
https://github.com/wotomas/VoiceRipple/tree/master/ripplelibrary
```

or you could clone for fork this git repository and check from the sample app.
```
https://github.com/wotomas/VoiceRipple.git
```

the api is really simple, but i haven't had enough time yet to clearly organize it.
you simply have to do the following:
1. call setMediaRecorder(MediaRecorder mediaRecorder) for the RippleView to record / observe voice recording status

2. give ripple settings for view you want to show. The higher the RippleRatio is, the bigger the ripple becomes, vise versa.
```java
voiceRipple.setRippleColor(ContextCompat.getColor(this, R.color.colorPrimary));
voiceRipple.setRippleSampleRate(Rate.LOW);
voiceRipple.setRippleDecayRate(Rate.HIGH);
voiceRipple.setBackgroundRippleRatio(1.4);
```
3. you can check from the MainActivity.class from the sample app where it calls setBackgroundRippleRatio() 
```
https://github.com/wotomas/VoiceRipple/blob/master/app/src/main/java/info/kimjihyok/voiceripple/MainActivity.java
```

**Comment by AndroidDeveloperLB** [comment]
I'm not asking how to use the library. I'm asking how it works behind the scenes

**Comment by wotomas** [comment]
Ahh sorry i miss read your question. You can check the handler part and the max amplitude part from the VoiceRippleView.class

**Comment by wotomas** [comment]
/**
   * Calculating decibels from amplitude requires the following: power_db = 20 * log10(amp / amp_ref);
   * 0db is the maximum, and everything else is negative
   * @param amplitude
   */
  private void drop(int amplitude) {
    int powerDb = (int)(20.0 * Math.log10((double) amplitude / AMPLITUDE_REFERENCE));

    // clip if change is below threshold
    final int THRESHOLD = (-1 * powerDb) / thresholdRate;

    if (THRESHOLD >= 0) {
      if (rippleRadius - THRESHOLD >= powerDb + MIN_RADIUS || powerDb + MIN_RADIUS >= rippleRadius + THRESHOLD) {
        rippleRadius = powerDb + MIN_RADIUS;
        backgroundRadius = (int) (rippleRadius * backgroundRippleRatio);
      } else {
        // if decreasing velocity reached 0, it should simply match with ripple radius
        if (((backgroundRadius - rippleRadius) / rippleDecayRate) == 0) {
          backgroundRadius = rippleRadius;
        } else {
          backgroundRadius = backgroundRadius - ((backgroundRadius - rippleRadius) / rippleDecayRate);
        }
      }

      invalidate();
    }
  }

**Comment by AndroidDeveloperLB** [comment]
Nice, and where do you get the value from the API of Android, to put into this function?

**Comment by wotomas** [comment]
The mediaRecorder from android provides api to get max amplitude value! You can check from the source code

**Comment by AndroidDeveloperLB** [comment]
In which file in the code?

**Comment by wotomas** [comment]
ripplelibrary/src/main/java/info/kimjihyok/ripplelibrary/VoiceRippleView.java

**Comment by AndroidDeveloperLB** [comment]
ok thank you!
