### ISSUE TITLE
运行不了，报错

### ISSUE THREAD

**Issue by StevenNick88** [wotomas/VoiceRipple#8]
compile "info.kimjihyok:voice-ripple-record-button:${voice-ripple-button-version}"

上面这行编译报错：
Error:(113, 0) Could not get unknown property 'voice' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
<a href="openFile:C:\Users\pradmin\Desktop\xender\BP3_xender\boomPlayer3.0\build.gradle">Open File</a>

**Comment by wotomas** [comment]
Thanks for the issue! the `:${voice-ripple-button-version}` should be replaced with the current version which is `0.1.2`

**Comment by wotomas** [comment]
will close for inactiveness
